### Get all users
GET http://localhost:3000/api/users

### Sign up user
POST http://localhost:3000/api/user/sign-up
Content-Type: application/json

{
"name": "John Doe",
"email": "john1@example.com",
"password": "securePassword123"
}

### Sign in user
POST http://localhost:3000/api/user/sign-in
Content-Type: application/json

{
  "email": "john1@example.com",
  "password": "securePassword123"
}